### ISSUE TITLE
Quick edit vs. Backend-Tools AddOn oder yForm Suche

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_quick_edit#1]
Erstmal, danke für das AddOn. Tolle Idee. 

Wenn das AddOn Backend-Tools installiert ist, passiert folgendes: 

<img width="1384" alt="Bildschirmfoto 2022-01-24 um 11 16 33" src="https://user-images.githubusercontent.com/791247/150764387-27920777-f35d-4a38-b8e2-20d3fb98f0cc.png">

**Comment by eaCe** [comment]
Danke für den Hinweis, werde es mal installieren und das Problem suchen.

**Comment by skerbis** [comment]
Auch bei eingeschalteter Suche
<img width="1627" alt="Bildschirmfoto 2022-01-24 um 11 30 53" src="https://user-images.githubusercontent.com/791247/150766767-ec5db25b-5054-4df2-8832-f9c65e6342bd.png">

**Comment by AWqxKAWERbXo** [comment]
@eaCe wie rufst du denn das Formular ab? die URL des Table Managers oder generierst du es über YOrm? Letzteres würde ich empfehlen.

**Comment by eaCe** [comment]
@alxndr-w es ist, wie bei den Aktionen, eine zusammengabeute URL. YOrm kenne ich nur zum Abfragen von Daten. Schau ich mir am Wochenende genauer an.

**Comment by AWqxKAWERbXo** [comment]
@eaCe das wird die zentrale Stelle für dich sein:

https://github.com/yakamara/redaxo_yform/blob/925d387eceaee04e52726ba7f88eaff5af24f42b/docs/04_yorm.md#datensatz-abfragen - als Ziel dann das Edit-Formular wählen oder über die rex_api arbeiten.

Schwierig könnte es noch werden mit inline-Relationen.

**Comment by eaCe** [comment]
Die Suche wird nun ausgeblendet. Backend-Tools habe ich noch nicht installiert, das muss ich noch ein mal ausprobieren.

**Comment by eaCe** [comment]
Backend-Tools sollten auch passen.

**Comment by AWqxKAWERbXo** [comment]
@eaCe voll gut!

Arbeitest du sonst auch mit GitHub? Du kannst, wenn du einen PR machst, Issues wie dieses automatisch schließen. Ansonsten melde dich gerne per Mail bei mir, falls ich dir ein paar Kniffe zeigen darf für die Addon-Entwicklung hier.

**Comment by eaCe** [comment]
@alxndr-w yo mache ich, das weiß ich auch, war nur nich sicher ob ich das direkt schließen soll :)
Sicher kann ich noch einiges lernen, vor allem bei yForm! Danke für dein Angebot, ich werde darauf zurück kommen.
