### ISSUE TITLE
Zappeln wenn geöffnet

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_quick_edit#2]
https://user-images.githubusercontent.com/791247/150764928-87fcfe1c-cbfd-42f1-b49f-8742fe302087.mov

Getestet in Safari 15.2

**Comment by eaCe** [comment]
Tritt das nur in Safari auf?

**Comment by skerbis** [comment]
In Chrome konnte ich es nicht feststellen.

**Comment by eaCe** [comment]
In der neuen Version gibt es kein Iframe mehr.
