### ISSUE TITLE
Ladezeit ist nicht quick

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_quick_edit#3]
Ich sehe hier aktuell keinen Vorteil. Die Ladezeit ist teils länger als das direkte Öffnen des Formulars.

**Comment by eaCe** [comment]
Die Ladezeit müsste der Ladezeit der Seite entsprechen. Es wird ja genau diese geladen.
Ich wüsste nicht wie ich das beschleunigen soll.
Man könnte JS oder CSS entfernen, aber ich weiß ja auch nicht welches zum Einsatz kommt.

**Comment by AWqxKAWERbXo** [comment]
@eaCe man könnte die Formulare schon beim Laden abfragen und ausblenden - aber je nachdem, wie viel das ist, könnte das bei zu vielen Feldern oder zu vielen Datensätzen auf einer Seite auch eine Performance-Einbuße sein.

**Comment by eaCe** [comment]
@alxndr-w danke für die Idee. Thomas hatte noch pjax im Sinne. Ich werde es am Wochenende mal probieren.

**Comment by eaCe** [comment]
Ich habe nun alles auf pjax umgebaut. Es sollte nun schneller sein, da die ganzen assets nicht noch ein mal geladen werden.
Vielleicht kannst du das noch mal neu einschätzen @skerbis

**Comment by skerbis** [comment]
gerade noch mal getestet: 👍🏻 ist nun quick
