### ISSUE TITLE
Settingsseite zur Tabellenauswahl

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_quick_edit#4]
Die Möglichkeit Tabellen zu ignorieren ist gut, aber: 
Aktuell wäre mir eine Positivliste lieber. Evtl. hat man so wie ich 30 Tabellen und nur 2 sollen bearbeitet werden.

**Comment by eaCe** [comment]
Dann würde ich das vielleicht mit einer Checkbox regeln, ob negativ oder positiv.

**Comment by skerbis** [comment]
eine reine Positiv-Liste finde ich leichter zu pflegen. (als Multiselect?)

**Comment by eaCe** [comment]
@skerbis hm, beim install dann immer erst mal alle auswählen? Beim Update muss ich dann mal schauen...

**Comment by skerbis** [comment]
würde sagen erstmal keine auswählen und den Admin entscheiden lassen. So wie's bei YForm Usability auch ist.

**Comment by eaCe** [comment]
Das muss man dann aber auch erst mal wissen :)

**Comment by AWqxKAWERbXo** [comment]
> So wie's bei YForm Usability auch ist.

Ist das so? Ich meine, das ist nicht so.

**Comment by eaCe** [comment]
Fast ein Jahr ignoriert. Dort sind alle aktiv, aber man hat eine Checkbox:
![grafik](https://user-images.githubusercontent.com/2708231/232877071-dcea1f9e-fffd-4dc0-b084-ea9a491f8cae.png)
