### ISSUE TITLE
YFORM 4 - Kein Speichern

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/yform_quick_edit#5]
In Yform 4 werden die schnell bearbeiteten Daten nicht gespeichert.

**Comment by eaCe** [comment]
Das ist mir noch nie aufgefallen :| Schau ich mir an!
@skerbis vielleicht hat sich etwas bei YForm geändet. Bei einem ersten Test ging es:
![yform](https://user-images.githubusercontent.com/2708231/192005326-8ea949e4-3a1e-4366-996c-f812e81b7836.gif)
Neuste YForm Version aus dem Installer, ebenso Quick Edit.

Wird Zeit für E2E Tests... :O

**Comment by skerbis** [comment]
bei "einfachen" Feldern klappt es. Bei CKE5 allerdings nicht.
Müsste man testen ob's auch bei anderen Editoren so ist.

**Comment by eaCe** [comment]
Alles klar, danke für den Hinweis.

**Comment by eaCe** [comment]
Scheint nur CKE5 zu betreffen. Bei Tiny und Redactor klappt es.

![editor](https://user-images.githubusercontent.com/2708231/192082471-a3e02bdc-9d40-49e1-8ebd-ba19441ee809.gif)

**Comment by eaCe** [comment]
@skerbis magst du mal die neuste scripts.js/den aktuellen Github Code testen?

**Comment by skerbis** [comment]
Juhuuu 👍🏻 Funktioniert.

**Comment by eaCe** [comment]
Bevor Quick Edit geschlossen wird setze ich noch mal alle Values von CKEditor manuell:

```javascript
if (typeof ckeditors !== 'undefined') {
    for (const ckeditorKey in ckeditors) {
        ckeditors[ckeditorKey].updateSourceElement();
    }
}
```
